### ISSUE TITLE
关于vnpy里面的chaince（hoo交易所）的ed25519加密签名没法通过认证问题

### ISSUE THREAD

**Issue by linyaofai** [nanlong/arithmetic_rs#1]
您好
我用你的代码，发现同样的参数，用你的代码生成的签名和官网生成的签名不一样的
无法完成签名认证，例如下面的代码，官网生成的结果如下
https://github.com/chaince/apidocs/blob/master/authentication.md  

from jwt import PyJWS
from chaince.edalgorithm import EDAlgorithm
payload = bytes('{"key": "cnc6666666666666", "iat": 1599999999}', encoding="utf-8")
secret_key = "CNC88888888888888888888888888888"
jws = PyJWS()
jws.register_algorithm('Ed25519', EDAlgorithm())
signature = jws.encode(payload, secret_key,algorithm='Ed25519')
print(signature)

运行你的vnchaince.py  交易所返回
on error
401 {'error': 'Unauthorized: invalid jwt signature'}

**Comment by nanlong** [comment]
你们有申请key吗？
